import { GridColDef } from "@mui/x-data-grid";

export type InventoryItem = {
  id: number;
  name: string;
  sku: string;
  category: string;
  quantity: number;
  price: number;
  location: string;
};

export const inventoryColumns: GridColDef<InventoryItem>[] = [
  { field: "id", headerName: "ID", width: 70, type: "number" },
  { field: "name", headerName: "Item Name", width: 200 },
  { field: "sku", headerName: "SKU", width: 120 },
  { field: "category", headerName: "Category", width: 150 },
  { field: "quantity", headerName: "Quantity", width: 100, type: "number" },
  { field: "price", headerName: "Price ($)", width: 100, type: "number" },
  { field: "location", headerName: "Location", width: 150 },
];

export const inventoryRows: InventoryItem[] = [
  {
    id: 1,
    name: "Laptop",
    sku: "LT1001",
    category: "Electronics",
    quantity: 12,
    price: 999.99,
    location: "Warehouse A",
  },
  {
    id: 2,
    name: "Keyboard",
    sku: "KB2001",
    category: "Accessories",
    quantity: 50,
    price: 29.99,
    location: "Warehouse B",
  },
  {
    id: 3,
    name: "Mouse",
    sku: "MS3001",
    category: "Accessories",
    quantity: 80,
    price: 19.99,
    location: "Warehouse A",
  },
  {
    id: 4,
    name: "Monitor",
    sku: "MN4001",
    category: "Electronics",
    quantity: 25,
    price: 149.99,
    location: "Warehouse C",
  },
  {
    id: 5,
    name: "Printer",
    sku: "PR5001",
    category: "Office Equipment",
    quantity: 10,
    price: 199.99,
    location: "Warehouse A",
  },
  {
    id: 6,
    name: "Router",
    sku: "RT6001",
    category: "Networking",
    quantity: 30,
    price: 89.99,
    location: "Warehouse B",
  },
  {
    id: 7,
    name: "USB Cable",
    sku: "UC7001",
    category: "Accessories",
    quantity: 100,
    price: 4.99,
    location: "Warehouse B",
  },
  {
    id: 8,
    name: "Chair",
    sku: "CH8001",
    category: "Furniture",
    quantity: 15,
    price: 79.99,
    location: "Warehouse C",
  },
  {
    id: 9,
    name: "Desk",
    sku: "DK9001",
    category: "Furniture",
    quantity: 20,
    price: 129.99,
    location: "Warehouse C",
  },
  {
    id: 10,
    name: "Projector",
    sku: "PJ1002",
    category: "Electronics",
    quantity: 5,
    price: 399.99,
    location: "Warehouse A",
  },
  {
    id: 11,
    name: "Tablet",
    sku: "TB1101",
    category: "Electronics",
    quantity: 18,
    price: 299.99,
    location: "Warehouse A",
  },
  {
    id: 12,
    name: "Webcam",
    sku: "WC1201",
    category: "Accessories",
    quantity: 40,
    price: 49.99,
    location: "Warehouse B",
  },
  {
    id: 13,
    name: "Headphones",
    sku: "HP1301",
    category: "Accessories",
    quantity: 60,
    price: 39.99,
    location: "Warehouse B",
  },
  {
    id: 14,
    name: "External HDD",
    sku: "HD1401",
    category: "Storage",
    quantity: 22,
    price: 79.99,
    location: "Warehouse A",
  },
  {
    id: 15,
    name: "Flash Drive",
    sku: "FD1501",
    category: "Storage",
    quantity: 150,
    price: 9.99,
    location: "Warehouse B",
  },
  {
    id: 16,
    name: "Smartphone",
    sku: "SP1601",
    category: "Electronics",
    quantity: 14,
    price: 599.99,
    location: "Warehouse A",
  },
  {
    id: 17,
    name: "Scanner",
    sku: "SC1701",
    category: "Office Equipment",
    quantity: 8,
    price: 149.99,
    location: "Warehouse C",
  },
  {
    id: 18,
    name: "Notebook",
    sku: "NB1801",
    category: "Stationery",
    quantity: 300,
    price: 1.99,
    location: "Warehouse B",
  },
  {
    id: 19,
    name: "Pen",
    sku: "PN1901",
    category: "Stationery",
    quantity: 500,
    price: 0.99,
    location: "Warehouse B",
  },
  {
    id: 20,
    name: "Label Printer",
    sku: "LP2001",
    category: "Office Equipment",
    quantity: 6,
    price: 89.99,
    location: "Warehouse A",
  },
];
